name: Docker Build InfoSections frontend

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Check the code
        uses: actions/checkout@v1
      -
        name: Push code
        run: |
            cd frontend
            echo "${{ secrets.DOCKERPW }}" | docker login -u "stephen10121" --password-stdin
            docker build -t stephen10121/infosectionsfrontend:1.${{ github.run_number }} .
            docker tag stephen10121/infosectionsfrontend:1.${{ github.run_number }} stephen10121/infosectionsfrontend:prod
            docker tag stephen10121/infosectionsfrontend:1.${{ github.run_number }} stephen10121/infosectionsfrontend:1.${{ github.run_number }}
            docker image push stephen10121/infosectionsfrontend:prod
            docker image push stephen10121/infosectionsfrontend:1.${{ github.run_number }}